@host=localhost:8080

GET {{host}}


###

GET {{host}}/ai/generate

###ction CheckinProject


GET {{host}}/ai/generateImage

###

GET {{host}}/ai/generate_palm

###

GET {{host}}/langchain/generate


###

GET {{host}}/langchain/generate/palm

###

GET {{host}}/langchain/generate/image

###

GET {{host}}/langchain/generate/edit-image
